#include <GenClass\fpml-asset-5-4\Bond.hpp>
#include <GenClass\fpml-asset-5-4\ActualPrice.hpp>
#include <GenClass\fpml-asset-5-4\AnyAssetReference.hpp>
#include <GenClass\fpml-asset-5-4\Asset.hpp>
#include <GenClass\fpml-asset-5-4\AssetMeasureType.hpp>
#include <GenClass\fpml-asset-5-4\AssetPool.hpp>
#include <GenClass\fpml-asset-5-4\AssetReference.hpp>
#include <GenClass\fpml-asset-5-4\BasicQuotation.hpp>
#include <GenClass\fpml-asset-5-4\Basket.hpp>
#include <GenClass\fpml-asset-5-4\BasketConstituent.hpp>
#include <GenClass\fpml-asset-5-4\BasketId.hpp>
#include <GenClass\fpml-asset-5-4\BasketName.hpp>
#include <GenClass\fpml-asset-5-4\Cash.hpp>
#include <GenClass\fpml-asset-5-4\Commission.hpp>
#include <GenClass\fpml-asset-5-4\Commodity.hpp>
#include <GenClass\fpml-asset-5-4\CommodityBase.hpp>
#include <GenClass\fpml-asset-5-4\CommodityBusinessCalendar.hpp>
#include <GenClass\fpml-asset-5-4\CommodityDetails.hpp>
#include <GenClass\fpml-asset-5-4\CommodityInformationSource.hpp>
#include <GenClass\fpml-asset-5-4\CommodityInformationProvider.hpp>
#include <GenClass\fpml-asset-5-4\ConstituentWeight.hpp>
#include <GenClass\fpml-asset-5-4\ConvertibleBond.hpp>
#include <GenClass\fpml-asset-5-4\CouponType.hpp>
#include <GenClass\fpml-asset-5-4\CurveInstrument.hpp>
#include <GenClass\fpml-asset-5-4\Deposit.hpp>
#include <GenClass\fpml-asset-5-4\DividendPayout.hpp>
#include <GenClass\fpml-asset-5-4\EquityAsset.hpp>
#include <GenClass\fpml-asset-5-4\ExchangeTraded.hpp>
#include <GenClass\fpml-asset-5-4\ExchangeTradedCalculatedPrice.hpp>
#include <GenClass\fpml-asset-5-4\ExchangeTradedContract.hpp>
#include <GenClass\fpml-asset-5-4\ExchangeTradedFund.hpp>
#include <GenClass\fpml-asset-5-4\FacilityType.hpp>
#include <GenClass\fpml-asset-5-4\Future.hpp>
#include <GenClass\fpml-asset-5-4\FutureId.hpp>
#include <GenClass\fpml-asset-5-4\FxConversion.hpp>
#include <GenClass\fpml-asset-5-4\FxRateAsset.hpp>
#include <GenClass\fpml-asset-5-4\IdentifiedAsset.hpp>
#include <GenClass\fpml-asset-5-4\Index.hpp>
#include <GenClass\fpml-asset-5-4\Lien.hpp>
#include <GenClass\fpml-asset-5-4\Loan.hpp>
#include <GenClass\fpml-asset-5-4\Mortgage.hpp>
#include <GenClass\fpml-asset-5-4\MortgageSector.hpp>
#include <GenClass\fpml-asset-5-4\MutualFund.hpp>
#include <GenClass\fpml-asset-5-4\PendingPayment.hpp>
#include <GenClass\fpml-asset-5-4\Price.hpp>
#include <GenClass\fpml-asset-5-4\PriceQuoteUnits.hpp>
#include <GenClass\fpml-asset-5-4\PricingModel.hpp>
#include <GenClass\fpml-asset-5-4\QuantityUnit.hpp>
#include <GenClass\fpml-asset-5-4\QuotationCharacteristics.hpp>
#include <GenClass\fpml-asset-5-4\QuoteTiming.hpp>
#include <GenClass\fpml-asset-5-4\RateIndex.hpp>
#include <GenClass\fpml-asset-5-4\ReportingCurrencyType.hpp>
#include <GenClass\fpml-asset-5-4\SimpleCreditDefaultSwap.hpp>
#include <GenClass\fpml-asset-5-4\SimpleFra.hpp>
#include <GenClass\fpml-asset-5-4\SimpleIRSwap.hpp>
#include <GenClass\fpml-asset-5-4\SingleUnderlyer.hpp>
#include <GenClass\fpml-asset-5-4\Underlyer.hpp>
#include <GenClass\fpml-asset-5-4\UnderlyingAsset.hpp>
#include <GenClass\fpml-asset-5-4\UnderlyingAssetTranche.hpp>
