#include <GenClass\ahn-product-1-0/all.hpp>
#include <GenClass\example-extension-5-4/all.hpp>
#include <GenClass\fpml-asset-5-4/all.hpp>
#include <GenClass\fpml-bond-option-5-4/all.hpp>
#include <GenClass\fpml-business-events-5-4/all.hpp>
#include <GenClass\fpml-cd-5-4/all.hpp>
#include <GenClass\fpml-com-5-4/all.hpp>
#include <GenClass\fpml-confirmation-processes-5-4/all.hpp>
#include <GenClass\fpml-correlation-swaps-5-4/all.hpp>
#include <GenClass\fpml-credit-event-notification-5-4/all.hpp>
#include <GenClass\fpml-dividend-swaps-5-4/all.hpp>
#include <GenClass\fpml-doc-5-4/all.hpp>
#include <GenClass\fpml-enum-5-4/all.hpp>
#include <GenClass\fpml-eq-shared-5-4/all.hpp>
#include <GenClass\fpml-eqd-5-4/all.hpp>
#include <GenClass\fpml-fx-5-4/all.hpp>
#include <GenClass\fpml-generic-5-4/all.hpp>
#include <GenClass\fpml-ird-5-4/all.hpp>
#include <GenClass\fpml-main-5-4/all.hpp>
#include <GenClass\fpml-mktenv-5-4/all.hpp>
#include <GenClass\fpml-msg-5-4/all.hpp>
#include <GenClass\fpml-option-shared-5-4/all.hpp>
#include <GenClass\fpml-return-swaps-5-4/all.hpp>
#include <GenClass\fpml-riskdef-5-4/all.hpp>
#include <GenClass\fpml-shared-5-4/all.hpp>
#include <GenClass\fpml-standard-5-4/all.hpp>
#include <GenClass\fpml-valuation-5-4/all.hpp>
#include <GenClass\fpml-variance-swaps-5-4/all.hpp>
#include <GenClass\xmldsig-core-schema/all.hpp>
