#include <GenClass\fpml-cd-5-4\AdditionalFixedPayments.hpp>
#include <GenClass\fpml-cd-5-4\AdditionalTerm.hpp>
#include <GenClass\fpml-cd-5-4\AdjustedPaymentDates.hpp>
#include <GenClass\fpml-cd-5-4\BasketReferenceInformation.hpp>
#include <GenClass\fpml-cd-5-4\CalculationAmount.hpp>
#include <GenClass\fpml-cd-5-4\CashSettlementTerms.hpp>
#include <GenClass\fpml-cd-5-4\CreditDefaultSwap.hpp>
#include <GenClass\fpml-cd-5-4\CreditDefaultSwapOption.hpp>
#include <GenClass\fpml-cd-5-4\CreditOptionStrike.hpp>
#include <GenClass\fpml-cd-5-4\DeliverableObligations.hpp>
#include <GenClass\fpml-cd-5-4\EntityType.hpp>
#include <GenClass\fpml-cd-5-4\FeeLeg.hpp>
#include <GenClass\fpml-cd-5-4\FixedAmountCalculation.hpp>
#include <GenClass\fpml-cd-5-4\FixedRate.hpp>
#include <GenClass\fpml-cd-5-4\FixedRateReference.hpp>
#include <GenClass\fpml-cd-5-4\FloatingAmountEvents.hpp>
#include <GenClass\fpml-cd-5-4\FloatingAmountProvisions.hpp>
#include <GenClass\fpml-cd-5-4\GeneralTerms.hpp>
#include <GenClass\fpml-cd-5-4\IndexAnnexSource.hpp>
#include <GenClass\fpml-cd-5-4\IndexId.hpp>
#include <GenClass\fpml-cd-5-4\IndexName.hpp>
#include <GenClass\fpml-cd-5-4\IndexReferenceInformation.hpp>
#include <GenClass\fpml-cd-5-4\InitialPayment.hpp>
#include <GenClass\fpml-cd-5-4\InterestShortFall.hpp>
#include <GenClass\fpml-cd-5-4\LimitedCreditDefaultSwap.hpp>
#include <GenClass\fpml-cd-5-4\LoanParticipation.hpp>
#include <GenClass\fpml-cd-5-4\MatrixSource.hpp>
#include <GenClass\fpml-cd-5-4\MultipleValuationDates.hpp>
#include <GenClass\fpml-cd-5-4\NotDomesticCurrency.hpp>
#include <GenClass\fpml-cd-5-4\Obligations.hpp>
#include <GenClass\fpml-cd-5-4\PCDeliverableObligationCharac.hpp>
#include <GenClass\fpml-cd-5-4\PeriodicPayment.hpp>
#include <GenClass\fpml-cd-5-4\PhysicalSettlementPeriod.hpp>
#include <GenClass\fpml-cd-5-4\PhysicalSettlementTerms.hpp>
#include <GenClass\fpml-cd-5-4\ProtectionTerms.hpp>
#include <GenClass\fpml-cd-5-4\ProtectionTermsReference.hpp>
#include <GenClass\fpml-cd-5-4\ReferenceInformation.hpp>
#include <GenClass\fpml-cd-5-4\ReferenceObligation.hpp>
#include <GenClass\fpml-cd-5-4\ReferencePair.hpp>
#include <GenClass\fpml-cd-5-4\ReferencePool.hpp>
#include <GenClass\fpml-cd-5-4\ReferencePoolItem.hpp>
#include <GenClass\fpml-cd-5-4\SettledEntityMatrix.hpp>
#include <GenClass\fpml-cd-5-4\SettlementTerms.hpp>
#include <GenClass\fpml-cd-5-4\SettlementTermsReference.hpp>
#include <GenClass\fpml-cd-5-4\SinglePayment.hpp>
#include <GenClass\fpml-cd-5-4\SingleValuationDate.hpp>
#include <GenClass\fpml-cd-5-4\SpecifiedCurrency.hpp>
#include <GenClass\fpml-cd-5-4\Tranche.hpp>
#include <GenClass\fpml-cd-5-4\ValuationDate.hpp>
