#include <GenClass\fpml-doc-5-4\QueryParameterValue.hpp>
#include <GenClass\fpml-doc-5-4\Allocation.hpp>
#include <GenClass\fpml-doc-5-4\AllocationReportingStatus.hpp>
#include <GenClass\fpml-doc-5-4\Allocations.hpp>
#include <GenClass\fpml-doc-5-4\Approval.hpp>
#include <GenClass\fpml-doc-5-4\Approvals.hpp>
#include <GenClass\fpml-doc-5-4\BestFitTrade.hpp>
#include <GenClass\fpml-doc-5-4\ClearingStatusValue.hpp>
#include <GenClass\fpml-doc-5-4\Collateral.hpp>
#include <GenClass\fpml-doc-5-4\CollateralizationType.hpp>
#include <GenClass\fpml-doc-5-4\ConfirmationMethod.hpp>
#include <GenClass\fpml-doc-5-4\ContractId.hpp>
#include <GenClass\fpml-doc-5-4\ContractIdentifier.hpp>
#include <GenClass\fpml-doc-5-4\CreditDerivativesNotices.hpp>
#include <GenClass\fpml-doc-5-4\CreditDocument.hpp>
#include <GenClass\fpml-doc-5-4\DataDocument.hpp>
#include <GenClass\fpml-doc-5-4\Document.hpp>
#include <GenClass\fpml-doc-5-4\EndUserExceptionDeclaration.hpp>
#include <GenClass\fpml-doc-5-4\ExecutionDateTime.hpp>
#include <GenClass\fpml-doc-5-4\ExecutionType.hpp>
#include <GenClass\fpml-doc-5-4\ExecutionVenueType.hpp>
#include <GenClass\fpml-doc-5-4\FirstPeriodStartDate.hpp>
#include <GenClass\fpml-doc-5-4\IndependentAmount.hpp>
#include <GenClass\fpml-doc-5-4\InstrumentTradeDetails.hpp>
#include <GenClass\fpml-doc-5-4\InstrumentTradeQuantity.hpp>
#include <GenClass\fpml-doc-5-4\InstrumentTradePricing.hpp>
#include <GenClass\fpml-doc-5-4\InstrumentTradePrincipal.hpp>
#include <GenClass\fpml-doc-5-4\IssuerId.hpp>
#include <GenClass\fpml-doc-5-4\LinkId.hpp>
#include <GenClass\fpml-doc-5-4\NetAndGross.hpp>
#include <GenClass\fpml-doc-5-4\OrganizationCharacteristic.hpp>
#include <GenClass\fpml-doc-5-4\PartyPortfolioName.hpp>
#include <GenClass\fpml-doc-5-4\PartyTradeIdentifier.hpp>
#include <GenClass\fpml-doc-5-4\PartyTradeIdentifiers.hpp>
#include <GenClass\fpml-doc-5-4\PartyTradeInformation.hpp>
#include <GenClass\fpml-doc-5-4\PaymentDetail.hpp>
#include <GenClass\fpml-doc-5-4\PaymentRule.hpp>
#include <GenClass\fpml-doc-5-4\PercentageRule.hpp>
#include <GenClass\fpml-doc-5-4\Portfolio.hpp>
#include <GenClass\fpml-doc-5-4\PortfolioName.hpp>
#include <GenClass\fpml-doc-5-4\QueryParameter.hpp>
#include <GenClass\fpml-doc-5-4\QueryParameterId.hpp>
#include <GenClass\fpml-doc-5-4\QueryParameterOperator.hpp>
#include <GenClass\fpml-doc-5-4\QueryPortfolio.hpp>
#include <GenClass\fpml-doc-5-4\RegulatorId.hpp>
#include <GenClass\fpml-doc-5-4\ReportingPurpose.hpp>
#include <GenClass\fpml-doc-5-4\ReportingRegime.hpp>
#include <GenClass\fpml-doc-5-4\ReportingRegimeName.hpp>
#include <GenClass\fpml-doc-5-4\ReportingRole.hpp>
#include <GenClass\fpml-doc-5-4\Strategy.hpp>
#include <GenClass\fpml-doc-5-4\StrategyComponentIdentification.hpp>
#include <GenClass\fpml-doc-5-4\SupervisorRegistration.hpp>
#include <GenClass\fpml-doc-5-4\SupervisoryBody.hpp>
#include <GenClass\fpml-doc-5-4\TimestampTypeScheme.hpp>
#include <GenClass\fpml-doc-5-4\Trade.hpp>
#include <GenClass\fpml-doc-5-4\TradeCategory.hpp>
#include <GenClass\fpml-doc-5-4\TradeDifference.hpp>
#include <GenClass\fpml-doc-5-4\TradeHeader.hpp>
#include <GenClass\fpml-doc-5-4\TradeId.hpp>
#include <GenClass\fpml-doc-5-4\TradeIdentifier.hpp>
#include <GenClass\fpml-doc-5-4\ProductComponentIdentifier.hpp>
#include <GenClass\fpml-doc-5-4\TradeProcessingTimestamps.hpp>
#include <GenClass\fpml-doc-5-4\Trader.hpp>
#include <GenClass\fpml-doc-5-4\TradeTimestamp.hpp>
#include <GenClass\fpml-doc-5-4\TransactionCharacteristic.hpp>
#include <GenClass\fpml-doc-5-4\Validation.hpp>
#include <GenClass\fpml-doc-5-4\VerificationMethod.hpp>
#include <GenClass\fpml-doc-5-4\VersionedContractId.hpp>
#include <GenClass\fpml-doc-5-4\VersionedTradeId.hpp>
#include <GenClass\fpml-doc-5-4\.hpp>
