#include <GenClass\fpml-enum-5-4\AveragingInOutEnum.hpp>
#include <GenClass\fpml-enum-5-4\AveragingMethodEnum.hpp>
#include <GenClass\fpml-enum-5-4\BreakageCostEnum.hpp>
#include <GenClass\fpml-enum-5-4\BullionTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\BusinessDayConventionEnum.hpp>
#include <GenClass\fpml-enum-5-4\CalendarSourceEnum.hpp>
#include <GenClass\fpml-enum-5-4\CalculationAgentPartyEnum.hpp>
#include <GenClass\fpml-enum-5-4\CashPhysicalEnum.hpp>
#include <GenClass\fpml-enum-5-4\CollateralValueAllocationEnum.hpp>
#include <GenClass\fpml-enum-5-4\CommissionDenominationEnum.hpp>
#include <GenClass\fpml-enum-5-4\CommodityBullionSettlementDisruptionEnum.hpp>
#include <GenClass\fpml-enum-5-4\CommodityDayTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\CommodityPayRelativeToEnum.hpp>
#include <GenClass\fpml-enum-5-4\CompoundingMethodEnum.hpp>
#include <GenClass\fpml-enum-5-4\DayOfWeekEnum.hpp>
#include <GenClass\fpml-enum-5-4\DayTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\DealtCurrencyEnum.hpp>
#include <GenClass\fpml-enum-5-4\DeliveryDatesEnum.hpp>
#include <GenClass\fpml-enum-5-4\DeliveryTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\DifferenceSeverityEnum.hpp>
#include <GenClass\fpml-enum-5-4\DifferenceTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\DiscountingTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\DisruptionFallbacksEnum.hpp>
#include <GenClass\fpml-enum-5-4\DividendAmountTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\DividendCompositionEnum.hpp>
#include <GenClass\fpml-enum-5-4\DividendDateReferenceEnum.hpp>
#include <GenClass\fpml-enum-5-4\DividendEntitlementEnum.hpp>
#include <GenClass\fpml-enum-5-4\DividendPeriodEnum.hpp>
#include <GenClass\fpml-enum-5-4\DualCurrencyStrikeQuoteBasisEnum.hpp>
#include <GenClass\fpml-enum-5-4\ElectricityProductTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\EnvironmentalAbandonmentOfSchemeEnum.hpp>
#include <GenClass\fpml-enum-5-4\EnvironmentalProductTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\EquityOptionTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\ExerciseStyleEnum.hpp>
#include <GenClass\fpml-enum-5-4\FeeElectionEnum.hpp>
#include <GenClass\fpml-enum-5-4\FlatRateEnum.hpp>
#include <GenClass\fpml-enum-5-4\FPVFinalPriceElectionFallbackEnum.hpp>
#include <GenClass\fpml-enum-5-4\FraDiscountingEnum.hpp>
#include <GenClass\fpml-enum-5-4\FrequencyTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\FxBarrierTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\FxTenorPeriodEnum.hpp>
#include <GenClass\fpml-enum-5-4\GasProductTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\IndependentAmountConventionEnum.hpp>
#include <GenClass\fpml-enum-5-4\IndexEventConsequenceEnum.hpp>
#include <GenClass\fpml-enum-5-4\InterestCalculationMethodEnum.hpp>
#include <GenClass\fpml-enum-5-4\InterestCalculationTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\InterestMethodEnum.hpp>
#include <GenClass\fpml-enum-5-4\InterestShortfallCapEnum.hpp>
#include <GenClass\fpml-enum-5-4\InterpolationPeriodEnum.hpp>
#include <GenClass\fpml-enum-5-4\LengthUnitEnum.hpp>
#include <GenClass\fpml-enum-5-4\LoadTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\MarketDisruptionEventsEnum.hpp>
#include <GenClass\fpml-enum-5-4\MarkToMarketConventionEnum.hpp>
#include <GenClass\fpml-enum-5-4\MetalTitleEnum.hpp>
#include <GenClass\fpml-enum-5-4\MethodOfAdjustmentEnum.hpp>
#include <GenClass\fpml-enum-5-4\NationalisationOrInsolvencyOrDelistingEventEnum.hpp>
#include <GenClass\fpml-enum-5-4\NegativeInterestRateTreatmentEnum.hpp>
#include <GenClass\fpml-enum-5-4\NonCashDividendTreatmentEnum.hpp>
#include <GenClass\fpml-enum-5-4\NotionalAdjustmentEnum.hpp>
#include <GenClass\fpml-enum-5-4\ObligationCategoryEnum.hpp>
#include <GenClass\fpml-enum-5-4\OptionTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\PayerReceiverEnum.hpp>
#include <GenClass\fpml-enum-5-4\PayoutEnum.hpp>
#include <GenClass\fpml-enum-5-4\PayRelativeToEnum.hpp>
#include <GenClass\fpml-enum-5-4\PeriodEnum.hpp>
#include <GenClass\fpml-enum-5-4\PeriodExtendedEnum.hpp>
#include <GenClass\fpml-enum-5-4\PositionOriginEnum.hpp>
#include <GenClass\fpml-enum-5-4\PositionStatusEnum.hpp>
#include <GenClass\fpml-enum-5-4\PremiumQuoteBasisEnum.hpp>
#include <GenClass\fpml-enum-5-4\PremiumTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\PriceExpressionEnum.hpp>
#include <GenClass\fpml-enum-5-4\PutCallEnum.hpp>
#include <GenClass\fpml-enum-5-4\QuotationRateTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\QuotationSideEnum.hpp>
#include <GenClass\fpml-enum-5-4\QuotationStyleEnum.hpp>
#include <GenClass\fpml-enum-5-4\QuoteBasisEnum.hpp>
#include <GenClass\fpml-enum-5-4\RateTreatmentEnum.hpp>
#include <GenClass\fpml-enum-5-4\RealisedVarianceMethodEnum.hpp>
#include <GenClass\fpml-enum-5-4\ResetRelativeToEnum.hpp>
#include <GenClass\fpml-enum-5-4\ReturnTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\RollConventionEnum.hpp>
#include <GenClass\fpml-enum-5-4\RoundingDirectionEnum.hpp>
#include <GenClass\fpml-enum-5-4\SettlementPeriodDurationEnum.hpp>
#include <GenClass\fpml-enum-5-4\SettlementTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\ShareExtraordinaryEventEnum.hpp>
#include <GenClass\fpml-enum-5-4\SpecifiedPriceEnum.hpp>
#include <GenClass\fpml-enum-5-4\StandardSettlementStyleEnum.hpp>
#include <GenClass\fpml-enum-5-4\StepRelativeToEnum.hpp>
#include <GenClass\fpml-enum-5-4\StubPeriodTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\StrikeQuoteBasisEnum.hpp>
#include <GenClass\fpml-enum-5-4\TelephoneTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\ThresholdTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\TimeTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\TriggerConditionEnum.hpp>
#include <GenClass\fpml-enum-5-4\TriggerTimeTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\TriggerTypeEnum.hpp>
#include <GenClass\fpml-enum-5-4\TouchConditionEnum.hpp>
#include <GenClass\fpml-enum-5-4\ValuationMethodEnum.hpp>
#include <GenClass\fpml-enum-5-4\WeatherSettlementLevelEnum.hpp>
#include <GenClass\fpml-enum-5-4\WeeklyRollConventionEnum.hpp>
