#include <GenClass\fpml-fx-5-4\PointValue.hpp>
#include <GenClass\fpml-fx-5-4\CrossRate.hpp>
#include <GenClass\fpml-fx-5-4\CutName.hpp>
#include <GenClass\fpml-fx-5-4\DualCurrencyFeature.hpp>
#include <GenClass\fpml-fx-5-4\DualCurrencyStrikePrice.hpp>
#include <GenClass\fpml-fx-5-4\ExchangeRate.hpp>
#include <GenClass\fpml-fx-5-4\FxAmericanExercise.hpp>
#include <GenClass\fpml-fx-5-4\FxAsianFeature.hpp>
#include <GenClass\fpml-fx-5-4\FxAverageRateObservation.hpp>
#include <GenClass\fpml-fx-5-4\FxAverageRateObservationSchedule.hpp>
#include <GenClass\fpml-fx-5-4\FxBarrierFeature.hpp>
#include <GenClass\fpml-fx-5-4\FxBoundary.hpp>
#include <GenClass\fpml-fx-5-4\FxDigitalAmericanExercise.hpp>
#include <GenClass\fpml-fx-5-4\FxDigitalOption.hpp>
#include <GenClass\fpml-fx-5-4\FxEuropeanExercise.hpp>
#include <GenClass\fpml-fx-5-4\FxMultipleExercise.hpp>
#include <GenClass\fpml-fx-5-4\FxOption.hpp>
#include <GenClass\fpml-fx-5-4\FxOptionFeatures.hpp>
#include <GenClass\fpml-fx-5-4\FxOptionPayout.hpp>
#include <GenClass\fpml-fx-5-4\FxOptionPremium.hpp>
#include <GenClass\fpml-fx-5-4\FxSingleLeg.hpp>
#include <GenClass\fpml-fx-5-4\FxStrikePrice.hpp>
#include <GenClass\fpml-fx-5-4\FxSwap.hpp>
#include <GenClass\fpml-fx-5-4\FxSwapLeg.hpp>
#include <GenClass\fpml-fx-5-4\FxTouch.hpp>
#include <GenClass\fpml-fx-5-4\FxTrigger.hpp>
#include <GenClass\fpml-fx-5-4\LowerBound.hpp>
#include <GenClass\fpml-fx-5-4\MoneyReference.hpp>
#include <GenClass\fpml-fx-5-4\ObservationSchedule.hpp>
#include <GenClass\fpml-fx-5-4\PremiumQuote.hpp>
#include <GenClass\fpml-fx-5-4\TermDeposit.hpp>
#include <GenClass\fpml-fx-5-4\TermDepositFeatures.hpp>
#include <GenClass\fpml-fx-5-4\UpperBound.hpp>
#include <GenClass\fpml-fx-5-4\.hpp>
#include <GenClass\fpml-fx-5-4\.hpp>
#include <GenClass\fpml-fx-5-4\.hpp>
