#include <GenClass\RiskMonitor-0-1\GridCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\ProductInnerXml.hpp>
#include <GenClass\RiskMonitor-0-1\Root.hpp>
#include <GenClass\RiskMonitor-0-1\ParaRoot.hpp>
#include <GenClass\RiskMonitor-0-1\Pricing.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_result.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_valueResult.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_valueSideResult.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_greekResult.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_cashFlowsResult.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_greekUnderlying.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_cashFlowResult.hpp>
#include <GenClass\RiskMonitor-0-1\History.hpp>
#include <GenClass\RiskMonitor-0-1\Instrument.hpp>
#include <GenClass\RiskMonitor-0-1\Message.hpp>
#include <GenClass\RiskMonitor-0-1\MessageHeader.hpp>
#include <GenClass\RiskMonitor-0-1\MessageBody.hpp>
#include <GenClass\RiskMonitor-0-1\MaturityNotification.hpp>
#include <GenClass\RiskMonitor-0-1\ClearQueue.hpp>
#include <GenClass\RiskMonitor-0-1\GridCalculationStart.hpp>
#include <GenClass\RiskMonitor-0-1\CalculationServerInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_interface.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_swapInterface.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_parameter.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_standardPara.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_standardSwapPara.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_standardHifivePara.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_standardCreditPara.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_defaultCurve_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_discountCurve_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_yieldCurve.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_defaultCurve.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_interpolation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_rateData.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hifive.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_kiEventCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_simpleKiEventCalc.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_occReturnCalcInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_noOccReturnCalcInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_dualKiEventCalc.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_targetKiEventCalc.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hifive_subtype.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hifive_stepDown_ki.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_stepDownKI_subSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_compositeOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_stepDownKICustom.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_general.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiAssetCompositeOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_ScheduleGenerator.hpp>
#include <GenClass\RiskMonitor-0-1\GeneralScheduleInfo.hpp>
#include <GenClass\RiskMonitor-0-1\GeneralSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\GeneralScheduleDeatil.hpp>
#include <GenClass\RiskMonitor-0-1\General_scheduleDetail_fixedCoupon.hpp>
#include <GenClass\RiskMonitor-0-1\General_scheduleDetail_fixedAmount.hpp>
#include <GenClass\RiskMonitor-0-1\GeneralTerminationEvent.hpp>
#include <GenClass\RiskMonitor-0-1\GeneralTerminationEventDetail.hpp>
#include <GenClass\RiskMonitor-0-1\General_TerminationEventDetail_credit.hpp>
#include <GenClass\RiskMonitor-0-1\General_TerminationEventDetail_target.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedBond.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedBond_subtype.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedBond_constantRate.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedBond_subSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingBond.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingBond_subtype.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingBond_simple.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingBond_subSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_structuredBond.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_structuredBond_subtype.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_structuredBond_fixedAccrual.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_structuredBond_floatingAccrual.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_additionalOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_callableOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_puttableOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_noneOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_couponScheduleList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_couponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedCouponScheduleList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingCouponScheduleList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_floatingCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_condi_structuredCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_condi_structuredAccrualCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiCondi_structuredCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiCondi_structuredAccrualCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiCondi_multiRng_structuredAccrualCouponSchedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multi_rangeND.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_compositeOption_subtype.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiAsset_compositeOption_subtype.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaCallPut.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_upInOutCall.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_downInOutPut.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_digitalCallPut.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiAsset_vanillaCallPut.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiAsset_upInOutCall.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiAsset_downInOutPut.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_multiAsset_digitalCallPut.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fxForward.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fxSwap.hpp>
#include <GenClass\RiskMonitor-0-1\Fx_exchangeLeg.hpp>
#include <GenClass\RiskMonitor-0-1\ForwardContractInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_issueInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_noteInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_swapInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_swapLegInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_emptyInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_underlyingCalcInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceCalcInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_underlyingCalcInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_correlationInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_correlation_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_underlyingInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_underlyingModel_para.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_geometricBM.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_geometricBM_LocalVol.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hullWhiteOneFactor.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_rateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hullWhiteTwoFactor.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_forwardModel.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hestonModel.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_volSurface.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_underlyingCalcID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_selectedUnderlying.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_choiceUnderlyingCalcID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_maximumUnderlyingCalcID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_minimumUnderlyingCalcID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_averageUnderlyingCalcID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_orderUnderlyingCalcID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_underlyingInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_stockIndex.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_interestRate.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_indexType.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceSetList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceSet.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceCal_IDList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceCal_ID.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referSimpleCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_scheduleList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_schedule.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_simpleCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_complementReturnCalc.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_complementReturnCalc_Call.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_returnCalcInfo_CallableOption.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_choiceReturnCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_eventCalcInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_returnCalcInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_eventCalcInfo_Call.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_returnCalcInfo_Call.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_singleRangeEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_dualRangeEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_singleBarrierEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_dualBarrierEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_identityEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_constReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_kiScheduleList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_swapLeg.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_fixedRateSwapLeg.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_vanillaFloatingRateSwapLeg.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_structuredSwapLeg.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_creditEventSwapLeg.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_hifiveSwapLeg.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_creditEventInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_jointProbabilityTrait.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceInformationList.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceInformation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_referenceObligation.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_protectionTerms.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_creditEvents.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_obligations.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_structuredSwap.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_irs.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_counterUnderlyingCalcInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_crs.hpp>
#include <GenClass\RiskMonitor-0-1\Excel_cds.hpp>
#include <GenClass\RiskMonitor-0-1\InstPositionInfo.hpp>
#include <GenClass\RiskMonitor-0-1\InstrumentInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Group.hpp>
#include <GenClass\RiskMonitor-0-1\StandardInstrument.hpp>
#include <GenClass\RiskMonitor-0-1\StandardSwapInstrument.hpp>
#include <GenClass\RiskMonitor-0-1\CreditInstrument.hpp>
#include <GenClass\RiskMonitor-0-1\FixedBondInstrument.hpp>
#include <GenClass\RiskMonitor-0-1\BondInformation.hpp>
#include <GenClass\RiskMonitor-0-1\BondCouponInfo.hpp>
#include <GenClass\RiskMonitor-0-1\FixedRateType.hpp>
#include <GenClass\RiskMonitor-0-1\UnderlyingInformation.hpp>
#include <GenClass\RiskMonitor-0-1\IndexUnderInfo.hpp>
#include <GenClass\RiskMonitor-0-1\Index.hpp>
#include <GenClass\RiskMonitor-0-1\InterestRateIndex.hpp>
#include <GenClass\RiskMonitor-0-1\PayoffDateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\FixingDateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\RefVariableFixingDateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\FixedFixingDateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\NullFixingDateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\StockIndex.hpp>
#include <GenClass\RiskMonitor-0-1\SwapPayoffInfo.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaSwapPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\AutoCallableSwapPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\RecieveSwapPart.hpp>
#include <GenClass\RiskMonitor-0-1\PaySwapPart.hpp>
#include <GenClass\RiskMonitor-0-1\PayoffInfoAnalytic.hpp>
#include <GenClass\RiskMonitor-0-1\StandardPayoff_A.hpp>
#include <GenClass\RiskMonitor-0-1\EventTriggerList_A.hpp>
#include <GenClass\RiskMonitor-0-1\EventTrigger_A.hpp>
#include <GenClass\RiskMonitor-0-1\FixedRatePayoff_A.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaFloatingRatePayoff_A.hpp>
#include <GenClass\RiskMonitor-0-1\CapFloorOption.hpp>
#include <GenClass\RiskMonitor-0-1\CapOption.hpp>
#include <GenClass\RiskMonitor-0-1\FloorOption.hpp>
#include <GenClass\RiskMonitor-0-1\SwapPayoffInfoAnalytic.hpp>
#include <GenClass\RiskMonitor-0-1\InterestRateSwapPayoff_A.hpp>
#include <GenClass\RiskMonitor-0-1\RecieveSwapPart_A.hpp>
#include <GenClass\RiskMonitor-0-1\PaySwapPart_A.hpp>
#include <GenClass\RiskMonitor-0-1\PayoffInfo.hpp>
#include <GenClass\RiskMonitor-0-1\PreDefinedVariableList.hpp>
#include <GenClass\RiskMonitor-0-1\AutoCallablePayoff.hpp>
#include <GenClass\RiskMonitor-0-1\StepDownKIPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\StepDownNoKIPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\StopLossPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\StopLossReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\CompositeSumOptionPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\OptionPayoffFunction.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaCallFunction.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaPutFunction.hpp>
#include <GenClass\RiskMonitor-0-1\StandardOption.hpp>
#include <GenClass\RiskMonitor-0-1\SingleBarrier.hpp>
#include <GenClass\RiskMonitor-0-1\BarrierInfo.hpp>
#include <GenClass\RiskMonitor-0-1\ConstUpperBarrierInfo.hpp>
#include <GenClass\RiskMonitor-0-1\ConstLowerBarrierInfo.hpp>
#include <GenClass\RiskMonitor-0-1\ConstDualBarrierInfo.hpp>
#include <GenClass\RiskMonitor-0-1\BarrierDateInfo.hpp>
#include <GenClass\RiskMonitor-0-1\DateInformation.hpp>
#include <GenClass\RiskMonitor-0-1\DailyInterval.hpp>
#include <GenClass\RiskMonitor-0-1\DateList.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaCallOption.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaPutOption.hpp>
#include <GenClass\RiskMonitor-0-1\BarrierWithConstRebateCallOption.hpp>
#include <GenClass\RiskMonitor-0-1\BarrierWithConstRebatePutOption.hpp>
#include <GenClass\RiskMonitor-0-1\KiEventInfo.hpp>
#include <GenClass\RiskMonitor-0-1\NonKiEventInfo.hpp>
#include <GenClass\RiskMonitor-0-1\NoAutoCallReturnTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\RedemptionInfo.hpp>
#include <GenClass\RiskMonitor-0-1\AutoCallRedem.hpp>
#include <GenClass\RiskMonitor-0-1\MonthlyAutoCallRedem.hpp>
#include <GenClass\RiskMonitor-0-1\EventTriggerList.hpp>
#include <GenClass\RiskMonitor-0-1\EventTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\PreConditionEvent.hpp>
#include <GenClass\RiskMonitor-0-1\PreEventCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\JointEventCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\EventCalculationInfo.hpp>
#include <GenClass\RiskMonitor-0-1\AndEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\OrEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\AtLeastEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\AtMostEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\CountEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\EventCalculationList.hpp>
#include <GenClass\RiskMonitor-0-1\EventCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\RefVariable_eventOcc.hpp>
#include <GenClass\RiskMonitor-0-1\VariableEventInfo.hpp>
#include <GenClass\RiskMonitor-0-1\NullVariableEventInfo.hpp>
#include <GenClass\RiskMonitor-0-1\OverWriteVariableEventInfo.hpp>
#include <GenClass\RiskMonitor-0-1\AutoTerminationTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\JointSimpleCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\AndSimpleCal.hpp>
#include <GenClass\RiskMonitor-0-1\SingeSimpleCal.hpp>
#include <GenClass\RiskMonitor-0-1\UpperBarrierEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\LowerBarrierEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\DualBarrierEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceEventCal.hpp>
#include <GenClass\RiskMonitor-0-1\AutoCallConstReturnTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\AutoCallRangeReturnTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeConstReturnTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeReturnTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeReturnList.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeReturn.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeRateTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeEventList.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleRangeAccrualRateTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\FixedRateTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaRateTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\RedemptionNotionalTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaCouponTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleEventCouponTrigger.hpp>
#include <GenClass\RiskMonitor-0-1\ComplementReturnCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\ReturnCalculationInfo.hpp>
#include <GenClass\RiskMonitor-0-1\ReturnCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\CallPutCompositeReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\PreCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\VariableCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\VariableCalList.hpp>
#include <GenClass\RiskMonitor-0-1\Operator1DList.hpp>
#include <GenClass\RiskMonitor-0-1\Operator1D.hpp>
#include <GenClass\RiskMonitor-0-1\AdditionOper1D.hpp>
#include <GenClass\RiskMonitor-0-1\MultipleOper1D.hpp>
#include <GenClass\RiskMonitor-0-1\MaximumOper1D.hpp>
#include <GenClass\RiskMonitor-0-1\ConditionOperator.hpp>
#include <GenClass\RiskMonitor-0-1\RangeCondition1D.hpp>
#include <GenClass\RiskMonitor-0-1\OperatorND.hpp>
#include <GenClass\RiskMonitor-0-1\AdditionOperND.hpp>
#include <GenClass\RiskMonitor-0-1\MultipleOperND.hpp>
#include <GenClass\RiskMonitor-0-1\DivisionOperND.hpp>
#include <GenClass\RiskMonitor-0-1\MaximumOperND.hpp>
#include <GenClass\RiskMonitor-0-1\PostCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\ConstReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\RefVariable_returnValue.hpp>
#include <GenClass\RiskMonitor-0-1\VariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\NullVariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\ResetVariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\OverWriteVariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\AdditionVariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\PreDefinedVariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\DefinedVariableInfo.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\Complex1DReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\ComplexNDReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\ZeroReturnCal.hpp>
#include <GenClass\RiskMonitor-0-1\CreditDefaultSwapInstrument.hpp>
#include <GenClass\RiskMonitor-0-1\Header.hpp>
#include <GenClass\RiskMonitor-0-1\IssueInformation.hpp>
#include <GenClass\RiskMonitor-0-1\SwapInfo.hpp>
#include <GenClass\RiskMonitor-0-1\NoteInfo.hpp>
#include <GenClass\RiskMonitor-0-1\SecuritiesInfo.hpp>
#include <GenClass\RiskMonitor-0-1\OptionInfo.hpp>
#include <GenClass\RiskMonitor-0-1\CalculationAgent.hpp>
#include <GenClass\RiskMonitor-0-1\InterestRateSwapPayoff.hpp>
#include <GenClass\RiskMonitor-0-1\RateCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\VanillaRateCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\Range1D.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceCalculationInfo.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\FixingInformation.hpp>
#include <GenClass\RiskMonitor-0-1\Fixing.hpp>
#include <GenClass\RiskMonitor-0-1\RefVariable_referenceValue.hpp>
#include <GenClass\RiskMonitor-0-1\MaximumReferenceCal.hpp>
#include <GenClass\RiskMonitor-0-1\MinimumReferenceCal.hpp>
#include <GenClass\RiskMonitor-0-1\ChoiceReferenceCal.hpp>
#include <GenClass\RiskMonitor-0-1\IdentityReferenceCal.hpp>
#include <GenClass\RiskMonitor-0-1\RefVariableReferenceCal.hpp>
#include <GenClass\RiskMonitor-0-1\DailyReturnReferenceCal.hpp>
#include <GenClass\RiskMonitor-0-1\RateCouponCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\FixedRateCouponCalculation.hpp>
#include <GenClass\RiskMonitor-0-1\CalculationPeriodFrequency.hpp>
#include <GenClass\RiskMonitor-0-1\SwapStreamPara.hpp>
#include <GenClass\RiskMonitor-0-1\DiscountCurve_para.hpp>
#include <GenClass\RiskMonitor-0-1\YieldTermstructure.hpp>
#include <GenClass\RiskMonitor-0-1\Tenor.hpp>
#include <GenClass\RiskMonitor-0-1\RateData.hpp>
#include <GenClass\RiskMonitor-0-1\PricingParameter.hpp>
#include <GenClass\RiskMonitor-0-1\Method.hpp>
#include <GenClass\RiskMonitor-0-1\Monte.hpp>
#include <GenClass\RiskMonitor-0-1\StepDownKIResult.hpp>
#include <GenClass\RiskMonitor-0-1\UnderylingInfoResult.hpp>
#include <GenClass\RiskMonitor-0-1\NullResult.hpp>
#include <GenClass\RiskMonitor-0-1\UnderylingResult.hpp>
#include <GenClass\RiskMonitor-0-1\GbmGreekInfoResult.hpp>
#include <GenClass\RiskMonitor-0-1\GbmGreekResult.hpp>
#include <GenClass\RiskMonitor-0-1\HullWhiteGreekInfoResult.hpp>
#include <GenClass\RiskMonitor-0-1\HullWhiteGreekResult.hpp>
#include <GenClass\RiskMonitor-0-1\SimpleCashFlowResult.hpp>
#include <GenClass\RiskMonitor-0-1\CashFlowInfoResult.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceEntityInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceCurveList.hpp>
#include <GenClass\RiskMonitor-0-1\UnderlyingInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Underlying_para.hpp>
#include <GenClass\RiskMonitor-0-1\GeometricBM.hpp>
#include <GenClass\RiskMonitor-0-1\HullWhiteOneFactor.hpp>
#include <GenClass\RiskMonitor-0-1\ForwardModel.hpp>
#include <GenClass\RiskMonitor-0-1\CorrelationInfo_para.hpp>
#include <GenClass\RiskMonitor-0-1\Correlation_para.hpp>
#include <GenClass\RiskMonitor-0-1\JointProbabilityTrait.hpp>
#include <GenClass\RiskMonitor-0-1\NthDefaultTrait.hpp>
#include <GenClass\RiskMonitor-0-1\FittingYieldCurve.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceCurve.hpp>
#include <GenClass\RiskMonitor-0-1\EvaluationCurves.hpp>
#include <GenClass\RiskMonitor-0-1\CdsSpreadTermstructure.hpp>
#include <GenClass\RiskMonitor-0-1\StepDownKI_paraSetting.hpp>
#include <GenClass\RiskMonitor-0-1\GeometricBM_paraSetting.hpp>
#include <GenClass\RiskMonitor-0-1\HullWhite_paraSetting.hpp>
#include <GenClass\RiskMonitor-0-1\DiscountCurve_paraSetting.hpp>
#include <GenClass\RiskMonitor-0-1\InstHirachyInfo.hpp>
#include <GenClass\RiskMonitor-0-1\BookInformation.hpp>
#include <GenClass\RiskMonitor-0-1\InstrumentList.hpp>
#include <GenClass\RiskMonitor-0-1\PathInfo.hpp>
#include <GenClass\RiskMonitor-0-1\CreditPayoffInfo.hpp>
#include <GenClass\RiskMonitor-0-1\CreditDefaultSwap.hpp>
#include <GenClass\RiskMonitor-0-1\ProtectionPart.hpp>
#include <GenClass\RiskMonitor-0-1\CouponPart.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceInformationList.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceInformation.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceEntity.hpp>
#include <GenClass\RiskMonitor-0-1\ReferenceObligation.hpp>
#include <GenClass\RiskMonitor-0-1\Bond.hpp>
#include <GenClass\RiskMonitor-0-1\ProtectionTerms.hpp>
#include <GenClass\RiskMonitor-0-1\CalculationAmount.hpp>
#include <GenClass\RiskMonitor-0-1\CreditEvents.hpp>
#include <GenClass\RiskMonitor-0-1\Obligations.hpp>
#include <GenClass\RiskMonitor-0-1\HisoryData.hpp>
#include <GenClass\RiskMonitor-0-1\MarketData.hpp>
#include <GenClass\RiskMonitor-0-1\DataValueInfo.hpp>
#include <GenClass\RiskMonitor-0-1\DataValue.hpp>
