#include <GenClass\fpml-confirmation-processes-5-4\AllocationApproved.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\AllocationRefused.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\Clearing.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ClearingConfirmed.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ClearingRefused.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ClearingStatus.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ConfirmationAgreed.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ConfirmationDisputed.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ConfirmationRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ConfirmationStatus.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ConsentGranted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ConsentRefused.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\EventRequestAcknowledgement.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ExecutionAdvice.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ExecutionAdviceRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ExecutionNotification.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\ExecutionRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\MaturityNotification.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestAllocation.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestAllocationRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestClearing.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestClearingRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestConfirmation.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestConsent.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestConsentRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestExecution.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestExecutionRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestTradeReferenceInformationUpdate.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestTradeReferenceInformationUpdateRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\TradeChangeAdvice.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\TradeChangeAdviceRetracted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\TradeWrapper.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\RequestCollateralAllocation.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\CollateralAllocationAccepted.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\.hpp>
#include <GenClass\fpml-confirmation-processes-5-4\.hpp>
