#include <GenClass\fpml-shared-5-4\CorrelationValue.hpp>
#include <GenClass\fpml-shared-5-4\HourMinuteTime.hpp>
#include <GenClass\fpml-shared-5-4\Initial.hpp>
#include <GenClass\fpml-shared-5-4\NonNegativeDecimal.hpp>
#include <GenClass\fpml-shared-5-4\PositiveDecimal.hpp>
#include <GenClass\fpml-shared-5-4\RestrictedPercentage.hpp>
#include <GenClass\fpml-shared-5-4\Scheme.hpp>
#include <GenClass\fpml-shared-5-4\Token60.hpp>
#include <GenClass\fpml-shared-5-4\Account.hpp>
#include <GenClass\fpml-shared-5-4\AccountId.hpp>
#include <GenClass\fpml-shared-5-4\AccountName.hpp>
#include <GenClass\fpml-shared-5-4\AccountReference.hpp>
#include <GenClass\fpml-shared-5-4\AccountType.hpp>
#include <GenClass\fpml-shared-5-4\Address.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableDate.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableDate2.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableDates.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableDatesOrRelativeDateOffset.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableOrAdjustedDate.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableOrRelativeDate.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableOrRelativeDates.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableRelativeOrPeriodicDates.hpp>
#include <GenClass\fpml-shared-5-4\AdjustableRelativeOrPeriodicDates2.hpp>
#include <GenClass\fpml-shared-5-4\AdjustedRelativeDateOffset.hpp>
#include <GenClass\fpml-shared-5-4\AgreementType.hpp>
#include <GenClass\fpml-shared-5-4\AgreementVersion.hpp>
#include <GenClass\fpml-shared-5-4\AmericanExercise.hpp>
#include <GenClass\fpml-shared-5-4\AmountReference.hpp>
#include <GenClass\fpml-shared-5-4\AmountSchedule.hpp>
#include <GenClass\fpml-shared-5-4\AssetClass.hpp>
#include <GenClass\fpml-shared-5-4\AutomaticExercise.hpp>
#include <GenClass\fpml-shared-5-4\AverageDailyTradingVolumeLimit.hpp>
#include <GenClass\fpml-shared-5-4\Beneficiary.hpp>
#include <GenClass\fpml-shared-5-4\BermudaExercise.hpp>
#include <GenClass\fpml-shared-5-4\BrokerConfirmation.hpp>
#include <GenClass\fpml-shared-5-4\BrokerConfirmationType.hpp>
#include <GenClass\fpml-shared-5-4\BusinessCenter.hpp>
#include <GenClass\fpml-shared-5-4\BusinessCenters.hpp>
#include <GenClass\fpml-shared-5-4\BusinessCentersReference.hpp>
#include <GenClass\fpml-shared-5-4\BusinessCenterTime.hpp>
#include <GenClass\fpml-shared-5-4\BusinessDateRange.hpp>
#include <GenClass\fpml-shared-5-4\BusinessDayAdjustments.hpp>
#include <GenClass\fpml-shared-5-4\BusinessDayAdjustmentsReference.hpp>
#include <GenClass\fpml-shared-5-4\BusinessUnit.hpp>
#include <GenClass\fpml-shared-5-4\BusinessUnitReference.hpp>
#include <GenClass\fpml-shared-5-4\BusinessUnitRole.hpp>
#include <GenClass\fpml-shared-5-4\CalculationAgent.hpp>
#include <GenClass\fpml-shared-5-4\CalculationPeriodFrequency.hpp>
#include <GenClass\fpml-shared-5-4\CashflowId.hpp>
#include <GenClass\fpml-shared-5-4\CashflowNotional.hpp>
#include <GenClass\fpml-shared-5-4\CashflowType.hpp>
#include <GenClass\fpml-shared-5-4\CashSettlementReferenceBanks.hpp>
#include <GenClass\fpml-shared-5-4\ClearanceSystem.hpp>
#include <GenClass\fpml-shared-5-4\CollateralValueAllocation.hpp>
#include <GenClass\fpml-shared-5-4\ContactInformation.hpp>
#include <GenClass\fpml-shared-5-4\ContractualDefinitions.hpp>
#include <GenClass\fpml-shared-5-4\ContractualMatrix.hpp>
#include <GenClass\fpml-shared-5-4\ContractualSupplement.hpp>
#include <GenClass\fpml-shared-5-4\ContractualTermsSupplement.hpp>
#include <GenClass\fpml-shared-5-4\CorrespondentInformation.hpp>
#include <GenClass\fpml-shared-5-4\CountryCode.hpp>
#include <GenClass\fpml-shared-5-4\CreditSeniority.hpp>
#include <GenClass\fpml-shared-5-4\CreditSupportAgreement.hpp>
#include <GenClass\fpml-shared-5-4\CreditSupportAgreementIdentifier.hpp>
#include <GenClass\fpml-shared-5-4\CreditSupportAgreementType.hpp>
#include <GenClass\fpml-shared-5-4\CreditRating.hpp>
#include <GenClass\fpml-shared-5-4\Currency.hpp>
#include <GenClass\fpml-shared-5-4\DateList.hpp>
#include <GenClass\fpml-shared-5-4\DateOffset.hpp>
#include <GenClass\fpml-shared-5-4\DateRange.hpp>
#include <GenClass\fpml-shared-5-4\DateReference.hpp>
#include <GenClass\fpml-shared-5-4\DateTimeList.hpp>
#include <GenClass\fpml-shared-5-4\DayCountFraction.hpp>
#include <GenClass\fpml-shared-5-4\DeterminationMethod.hpp>
#include <GenClass\fpml-shared-5-4\DeterminationMethodReference.hpp>
#include <GenClass\fpml-shared-5-4\Documentation.hpp>
#include <GenClass\fpml-shared-5-4\Empty.hpp>
#include <GenClass\fpml-shared-5-4\EntityId.hpp>
#include <GenClass\fpml-shared-5-4\EntityName.hpp>
#include <GenClass\fpml-shared-5-4\EuropeanExercise.hpp>
#include <GenClass\fpml-shared-5-4\ExchangeId.hpp>
#include <GenClass\fpml-shared-5-4\Exercise.hpp>
#include <GenClass\fpml-shared-5-4\ExerciseFee.hpp>
#include <GenClass\fpml-shared-5-4\ExerciseFeeSchedule.hpp>
#include <GenClass\fpml-shared-5-4\ExerciseNotice.hpp>
#include <GenClass\fpml-shared-5-4\ExerciseProcedure.hpp>
#include <GenClass\fpml-shared-5-4\ExerciseProcedureOption.hpp>
#include <GenClass\fpml-shared-5-4\ExternalDocument.hpp>
#include <GenClass\fpml-shared-5-4\FloatingRate.hpp>
#include <GenClass\fpml-shared-5-4\FloatingRateCalculation.hpp>
#include <GenClass\fpml-shared-5-4\FloatingRateIndex.hpp>
#include <GenClass\fpml-shared-5-4\ForecastRateIndex.hpp>
#include <GenClass\fpml-shared-5-4\Formula.hpp>
#include <GenClass\fpml-shared-5-4\FormulaComponent.hpp>
#include <GenClass\fpml-shared-5-4\Frequency.hpp>
#include <GenClass\fpml-shared-5-4\FutureValueAmount.hpp>
#include <GenClass\fpml-shared-5-4\FxCashSettlement.hpp>
#include <GenClass\fpml-shared-5-4\FxFixing.hpp>
#include <GenClass\fpml-shared-5-4\FxRate.hpp>
#include <GenClass\fpml-shared-5-4\FxSpotRateSource.hpp>
#include <GenClass\fpml-shared-5-4\GenericAgreement.hpp>
#include <GenClass\fpml-shared-5-4\GoverningLaw.hpp>
#include <GenClass\fpml-shared-5-4\GrossCashflow.hpp>
#include <GenClass\fpml-shared-5-4\HTTPAttachmentReference.hpp>
#include <GenClass\fpml-shared-5-4\IdentifiedCurrency.hpp>
#include <GenClass\fpml-shared-5-4\IdentifiedCurrencyReference.hpp>
#include <GenClass\fpml-shared-5-4\IdentifiedDate.hpp>
#include <GenClass\fpml-shared-5-4\IdentifiedPayerReceiver.hpp>
#include <GenClass\fpml-shared-5-4\IdentifiedRate.hpp>
#include <GenClass\fpml-shared-5-4\IndustryClassification.hpp>
#include <GenClass\fpml-shared-5-4\InformationProvider.hpp>
#include <GenClass\fpml-shared-5-4\InformationSource.hpp>
#include <GenClass\fpml-shared-5-4\InstrumentId.hpp>
#include <GenClass\fpml-shared-5-4\InterestAccrualsCompoundingMethod.hpp>
#include <GenClass\fpml-shared-5-4\InterestAccrualsMethod.hpp>
#include <GenClass\fpml-shared-5-4\IntermediaryInformation.hpp>
#include <GenClass\fpml-shared-5-4\InterpolationMethod.hpp>
#include <GenClass\fpml-shared-5-4\Language.hpp>
#include <GenClass\fpml-shared-5-4\Leg.hpp>
#include <GenClass\fpml-shared-5-4\LegalEntity.hpp>
#include <GenClass\fpml-shared-5-4\LegalEntityReference.hpp>
#include <GenClass\fpml-shared-5-4\MainPublication.hpp>
#include <GenClass\fpml-shared-5-4\ManualExercise.hpp>
#include <GenClass\fpml-shared-5-4\MasterAgreement.hpp>
#include <GenClass\fpml-shared-5-4\MasterAgreementType.hpp>
#include <GenClass\fpml-shared-5-4\MasterAgreementVersion.hpp>
#include <GenClass\fpml-shared-5-4\MasterConfirmation.hpp>
#include <GenClass\fpml-shared-5-4\MasterConfirmationAnnexType.hpp>
#include <GenClass\fpml-shared-5-4\MasterConfirmationType.hpp>
#include <GenClass\fpml-shared-5-4\MatchId.hpp>
#include <GenClass\fpml-shared-5-4\Math.hpp>
#include <GenClass\fpml-shared-5-4\MatrixType.hpp>
#include <GenClass\fpml-shared-5-4\MatrixTerm.hpp>
#include <GenClass\fpml-shared-5-4\MimeType.hpp>
#include <GenClass\fpml-shared-5-4\Money.hpp>
#include <GenClass\fpml-shared-5-4\MoneyBase.hpp>
#include <GenClass\fpml-shared-5-4\MultipleExercise.hpp>
#include <GenClass\fpml-shared-5-4\NonNegativeAmountSchedule.hpp>
#include <GenClass\fpml-shared-5-4\NonNegativeMoney.hpp>
#include <GenClass\fpml-shared-5-4\NonNegativePayment.hpp>
#include <GenClass\fpml-shared-5-4\NonNegativeSchedule.hpp>
#include <GenClass\fpml-shared-5-4\NonNegativeStep.hpp>
#include <GenClass\fpml-shared-5-4\NotionalAmount.hpp>
#include <GenClass\fpml-shared-5-4\NotionalAmountReference.hpp>
#include <GenClass\fpml-shared-5-4\NotionalReference.hpp>
#include <GenClass\fpml-shared-5-4\Offset.hpp>
#include <GenClass\fpml-shared-5-4\OffsetPrevailingTime.hpp>
#include <GenClass\fpml-shared-5-4\OnBehalfOf.hpp>
#include <GenClass\fpml-shared-5-4\OrganizationType.hpp>
#include <GenClass\fpml-shared-5-4\OriginatingEvent.hpp>
#include <GenClass\fpml-shared-5-4\PartialExercise.hpp>
#include <GenClass\fpml-shared-5-4\Party.hpp>
#include <GenClass\fpml-shared-5-4\PartyId.hpp>
#include <GenClass\fpml-shared-5-4\PartyName.hpp>
#include <GenClass\fpml-shared-5-4\PartyReference.hpp>
#include <GenClass\fpml-shared-5-4\PartyRelationship.hpp>
#include <GenClass\fpml-shared-5-4\PartyRelationshipDocumentation.hpp>
#include <GenClass\fpml-shared-5-4\PartyRole.hpp>
#include <GenClass\fpml-shared-5-4\PartyRoleType.hpp>
#include <GenClass\fpml-shared-5-4\PersonReference.hpp>
#include <GenClass\fpml-shared-5-4\PartyTradeIdentifierReference.hpp>
#include <GenClass\fpml-shared-5-4\Payment.hpp>
#include <GenClass\fpml-shared-5-4\PaymentBase.hpp>
#include <GenClass\fpml-shared-5-4\PaymentBaseExtended.hpp>
#include <GenClass\fpml-shared-5-4\PaymentDetails.hpp>
#include <GenClass\fpml-shared-5-4\PaymentId.hpp>
#include <GenClass\fpml-shared-5-4\PaymentReference.hpp>
#include <GenClass\fpml-shared-5-4\PaymentType.hpp>
#include <GenClass\fpml-shared-5-4\Period.hpp>
#include <GenClass\fpml-shared-5-4\PeriodicDates.hpp>
#include <GenClass\fpml-shared-5-4\Person.hpp>
#include <GenClass\fpml-shared-5-4\PersonId.hpp>
#include <GenClass\fpml-shared-5-4\PersonRole.hpp>
#include <GenClass\fpml-shared-5-4\PositiveAmountSchedule.hpp>
#include <GenClass\fpml-shared-5-4\PositiveMoney.hpp>
#include <GenClass\fpml-shared-5-4\PositivePayment.hpp>
#include <GenClass\fpml-shared-5-4\PositiveSchedule.hpp>
#include <GenClass\fpml-shared-5-4\PositiveStep.hpp>
#include <GenClass\fpml-shared-5-4\PrevailingTime.hpp>
#include <GenClass\fpml-shared-5-4\PricingStructure.hpp>
#include <GenClass\fpml-shared-5-4\PricingStructureReference.hpp>
#include <GenClass\fpml-shared-5-4\PrincipalExchanges.hpp>
#include <GenClass\fpml-shared-5-4\Product.hpp>
#include <GenClass\fpml-shared-5-4\ProductId.hpp>
#include <GenClass\fpml-shared-5-4\ProductReference.hpp>
#include <GenClass\fpml-shared-5-4\ProductType.hpp>
#include <GenClass\fpml-shared-5-4\ProposedCollateralAllocation.hpp>
#include <GenClass\fpml-shared-5-4\QuotedCurrencyPair.hpp>
#include <GenClass\fpml-shared-5-4\Rate.hpp>
#include <GenClass\fpml-shared-5-4\RateObservation.hpp>
#include <GenClass\fpml-shared-5-4\RateReference.hpp>
#include <GenClass\fpml-shared-5-4\RateSourcePage.hpp>
#include <GenClass\fpml-shared-5-4\Reference.hpp>
#include <GenClass\fpml-shared-5-4\ReferenceAmount.hpp>
#include <GenClass\fpml-shared-5-4\ReferenceBank.hpp>
#include <GenClass\fpml-shared-5-4\ReferenceBankId.hpp>
#include <GenClass\fpml-shared-5-4\RelatedBusinessUnit.hpp>
#include <GenClass\fpml-shared-5-4\RelatedParty.hpp>
#include <GenClass\fpml-shared-5-4\RelatedPerson.hpp>
#include <GenClass\fpml-shared-5-4\RelativeDateOffset.hpp>
#include <GenClass\fpml-shared-5-4\RelativeDates.hpp>
#include <GenClass\fpml-shared-5-4\RelativeDateSequence.hpp>
#include <GenClass\fpml-shared-5-4\RequestedAction.hpp>
#include <GenClass\fpml-shared-5-4\RequiredIdentifierDate.hpp>
#include <GenClass\fpml-shared-5-4\ResetFrequency.hpp>
#include <GenClass\fpml-shared-5-4\Resource.hpp>
#include <GenClass\fpml-shared-5-4\ResourceId.hpp>
#include <GenClass\fpml-shared-5-4\ResourceLength.hpp>
#include <GenClass\fpml-shared-5-4\ResourceType.hpp>
#include <GenClass\fpml-shared-5-4\ReturnSwapNotionalAmountReference.hpp>
#include <GenClass\fpml-shared-5-4\Rounding.hpp>
#include <GenClass\fpml-shared-5-4\Routing.hpp>
#include <GenClass\fpml-shared-5-4\RoutingExplicitDetails.hpp>
#include <GenClass\fpml-shared-5-4\RoutingId.hpp>
#include <GenClass\fpml-shared-5-4\RoutingIds.hpp>
#include <GenClass\fpml-shared-5-4\RoutingIdsAndExplicitDetails.hpp>
#include <GenClass\fpml-shared-5-4\Schedule.hpp>
#include <GenClass\fpml-shared-5-4\ScheduleReference.hpp>
#include <GenClass\fpml-shared-5-4\SettlementInformation.hpp>
#include <GenClass\fpml-shared-5-4\SettlementInstruction.hpp>
#include <GenClass\fpml-shared-5-4\SettlementMethod.hpp>
#include <GenClass\fpml-shared-5-4\SettlementPriceDefaultElection.hpp>
#include <GenClass\fpml-shared-5-4\SettlementPriceSource.hpp>
#include <GenClass\fpml-shared-5-4\SettlementRateSource.hpp>
#include <GenClass\fpml-shared-5-4\SharedAmericanExercise.hpp>
#include <GenClass\fpml-shared-5-4\SimplePayment.hpp>
#include <GenClass\fpml-shared-5-4\SplitSettlement.hpp>
#include <GenClass\fpml-shared-5-4\SpreadSchedule.hpp>
#include <GenClass\fpml-shared-5-4\SpreadScheduleReference.hpp>
#include <GenClass\fpml-shared-5-4\SpreadScheduleType.hpp>
#include <GenClass\fpml-shared-5-4\Step.hpp>
#include <GenClass\fpml-shared-5-4\StepBase.hpp>
#include <GenClass\fpml-shared-5-4\StreetAddress.hpp>
#include <GenClass\fpml-shared-5-4\Strike.hpp>
#include <GenClass\fpml-shared-5-4\StrikeSchedule.hpp>
#include <GenClass\fpml-shared-5-4\Stub.hpp>
#include <GenClass\fpml-shared-5-4\StubValue.hpp>
#include <GenClass\fpml-shared-5-4\TelephoneNumber.hpp>
#include <GenClass\fpml-shared-5-4\TimezoneLocation.hpp>
#include <GenClass\fpml-shared-5-4\Unit.hpp>
