#include <GenClass\fpml-business-events-5-4\AbstractEvent.hpp>
#include <GenClass\fpml-business-events-5-4\AdditionalEvent.hpp>
#include <GenClass\fpml-business-events-5-4\BusinessEventIdentifier.hpp>
#include <GenClass\fpml-business-events-5-4\ChangeEvent.hpp>
#include <GenClass\fpml-business-events-5-4\CompressionActivity.hpp>
#include <GenClass\fpml-business-events-5-4\CompressionType.hpp>
#include <GenClass\fpml-business-events-5-4\ClearingStatusItem.hpp>
#include <GenClass\fpml-business-events-5-4\DeClear.hpp>
#include <GenClass\fpml-business-events-5-4\DeclearReason.hpp>
#include <GenClass\fpml-business-events-5-4\EventId.hpp>
#include <GenClass\fpml-business-events-5-4\EventProposedMatch.hpp>
#include <GenClass\fpml-business-events-5-4\EventsChoice.hpp>
#include <GenClass\fpml-business-events-5-4\IndexChange.hpp>
#include <GenClass\fpml-business-events-5-4\ImpliedTrade.hpp>
#include <GenClass\fpml-business-events-5-4\OptionExercise.hpp>
#include <GenClass\fpml-business-events-5-4\OptionExpiry.hpp>
#include <GenClass\fpml-business-events-5-4\OptionExpiryBase.hpp>
#include <GenClass\fpml-business-events-5-4\PhysicalExercise.hpp>
#include <GenClass\fpml-business-events-5-4\PhysicalSettlement.hpp>
#include <GenClass\fpml-business-events-5-4\RequestedWithdrawalAction.hpp>
#include <GenClass\fpml-business-events-5-4\TerminatingEvent.hpp>
#include <GenClass\fpml-business-events-5-4\TradeAmendmentContent.hpp>
#include <GenClass\fpml-business-events-5-4\TradeChangeBase.hpp>
#include <GenClass\fpml-business-events-5-4\TradeChangeContent.hpp>
#include <GenClass\fpml-business-events-5-4\TradeMaturity.hpp>
#include <GenClass\fpml-business-events-5-4\TradeNotionalChange.hpp>
#include <GenClass\fpml-business-events-5-4\TradeNovationContent.hpp>
#include <GenClass\fpml-business-events-5-4\TradeReferenceInformation.hpp>
#include <GenClass\fpml-business-events-5-4\Withdrawal.hpp>
#include <GenClass\fpml-business-events-5-4\WithdrawalReason.hpp>
