#include <GenClass\fpml-option-shared-5-4\Asian.hpp>
#include <GenClass\fpml-option-shared-5-4\AveragingObservationList.hpp>
#include <GenClass\fpml-option-shared-5-4\AveragingPeriod.hpp>
#include <GenClass\fpml-option-shared-5-4\AveragingSchedule.hpp>
#include <GenClass\fpml-option-shared-5-4\Barrier.hpp>
#include <GenClass\fpml-option-shared-5-4\CalendarSpread.hpp>
#include <GenClass\fpml-option-shared-5-4\ClassifiedPayment.hpp>
#include <GenClass\fpml-option-shared-5-4\Composite.hpp>
#include <GenClass\fpml-option-shared-5-4\CreditEventNotice.hpp>
#include <GenClass\fpml-option-shared-5-4\CreditEvents.hpp>
#include <GenClass\fpml-option-shared-5-4\CreditEventsReference.hpp>
#include <GenClass\fpml-option-shared-5-4\FailureToPay.hpp>
#include <GenClass\fpml-option-shared-5-4\FeaturePayment.hpp>
#include <GenClass\fpml-option-shared-5-4\FrequencyType.hpp>
#include <GenClass\fpml-option-shared-5-4\FxFeature.hpp>
#include <GenClass\fpml-option-shared-5-4\GracePeriodExtension.hpp>
#include <GenClass\fpml-option-shared-5-4\Knock.hpp>
#include <GenClass\fpml-option-shared-5-4\MarketDisruption.hpp>
#include <GenClass\fpml-option-shared-5-4\NotifyingParty.hpp>
#include <GenClass\fpml-option-shared-5-4\Option.hpp>
#include <GenClass\fpml-option-shared-5-4\OptionBase.hpp>
#include <GenClass\fpml-option-shared-5-4\OptionBaseExtended.hpp>
#include <GenClass\fpml-option-shared-5-4\OptionFeature.hpp>
#include <GenClass\fpml-option-shared-5-4\OptionNumericStrike.hpp>
#include <GenClass\fpml-option-shared-5-4\OptionStrike.hpp>
#include <GenClass\fpml-option-shared-5-4\PassThrough.hpp>
#include <GenClass\fpml-option-shared-5-4\PassThroughItem.hpp>
#include <GenClass\fpml-option-shared-5-4\Premium.hpp>
#include <GenClass\fpml-option-shared-5-4\PubliclyAvailableInformation.hpp>
#include <GenClass\fpml-option-shared-5-4\Quanto.hpp>
#include <GenClass\fpml-option-shared-5-4\Restructuring.hpp>
#include <GenClass\fpml-option-shared-5-4\RestructuringType.hpp>
#include <GenClass\fpml-option-shared-5-4\StrategyFeature.hpp>
#include <GenClass\fpml-option-shared-5-4\StrikeSpread.hpp>
#include <GenClass\fpml-option-shared-5-4\Trigger.hpp>
#include <GenClass\fpml-option-shared-5-4\TriggerEvent.hpp>
#include <GenClass\fpml-option-shared-5-4\WeightedAveragingObservation.hpp>
#include <GenClass\fpml-option-shared-5-4\.hpp>
#include <GenClass\fpml-option-shared-5-4\.hpp>
#include <GenClass\fpml-option-shared-5-4\.hpp>
#include <GenClass\fpml-option-shared-5-4\.hpp>
