#include <GenClass\fpml-com-5-4\AbsoluteTolerance.hpp>
#include <GenClass\fpml-com-5-4\AveragePriceLeg.hpp>
#include <GenClass\fpml-com-5-4\BullionDeliveryLocation.hpp>
#include <GenClass\fpml-com-5-4\BullionPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\CalculationPeriodsDatesReference.hpp>
#include <GenClass\fpml-com-5-4\CalculationPeriodsReference.hpp>
#include <GenClass\fpml-com-5-4\CalculationPeriodsScheduleReference.hpp>
#include <GenClass\fpml-com-5-4\CoalAttributeDecimal.hpp>
#include <GenClass\fpml-com-5-4\CoalAttributePercentage.hpp>
#include <GenClass\fpml-com-5-4\CoalDelivery.hpp>
#include <GenClass\fpml-com-5-4\CoalDeliveryPoint.hpp>
#include <GenClass\fpml-com-5-4\CoalPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\CoalProduct.hpp>
#include <GenClass\fpml-com-5-4\CoalProductSource.hpp>
#include <GenClass\fpml-com-5-4\CoalProductSpecifications.hpp>
#include <GenClass\fpml-com-5-4\CoalProductType.hpp>
#include <GenClass\fpml-com-5-4\CoalQualityAdjustments.hpp>
#include <GenClass\fpml-com-5-4\CoalStandardQuality.hpp>
#include <GenClass\fpml-com-5-4\CoalStandardQualitySchedule.hpp>
#include <GenClass\fpml-com-5-4\CoalTransportationEquipment.hpp>
#include <GenClass\fpml-com-5-4\CommodityAmericanExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityCalculationPeriodsSchedule.hpp>
#include <GenClass\fpml-com-5-4\CommodityDeliveryPeriods.hpp>
#include <GenClass\fpml-com-5-4\CommodityDeliveryPoint.hpp>
#include <GenClass\fpml-com-5-4\CommodityDeliveryRisk.hpp>
#include <GenClass\fpml-com-5-4\CommodityEuropeanExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityExercisePeriods.hpp>
#include <GenClass\fpml-com-5-4\CommodityExpireRelativeToEvent.hpp>
#include <GenClass\fpml-com-5-4\CommodityFixedPriceSchedule.hpp>
#include <GenClass\fpml-com-5-4\CommodityForward.hpp>
#include <GenClass\fpml-com-5-4\CommodityForwardLeg.hpp>
#include <GenClass\fpml-com-5-4\CommodityFrequencyType.hpp>
#include <GenClass\fpml-com-5-4\CommodityFx.hpp>
#include <GenClass\fpml-com-5-4\CommodityFxType.hpp>
#include <GenClass\fpml-com-5-4\CommodityHub.hpp>
#include <GenClass\fpml-com-5-4\CommodityHubCode.hpp>
#include <GenClass\fpml-com-5-4\CommodityMarketDisruption.hpp>
#include <GenClass\fpml-com-5-4\CommodityMetalBrand.hpp>
#include <GenClass\fpml-com-5-4\CommodityMetalBrandManager.hpp>
#include <GenClass\fpml-com-5-4\CommodityMetalBrandName.hpp>
#include <GenClass\fpml-com-5-4\CommodityMetalGrade.hpp>
#include <GenClass\fpml-com-5-4\CommodityMetalProducer.hpp>
#include <GenClass\fpml-com-5-4\CommodityMetalShape.hpp>
#include <GenClass\fpml-com-5-4\CommodityMultipleExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityNotionalQuantity.hpp>
#include <GenClass\fpml-com-5-4\CommodityNotionalQuantitySchedule.hpp>
#include <GenClass\fpml-com-5-4\CommodityOption.hpp>
#include <GenClass\fpml-com-5-4\CommodityPayRelativeToEvent.hpp>
#include <GenClass\fpml-com-5-4\CommodityPhysicalAmericanExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityPhysicalEuropeanExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityPhysicalExercise.hpp>
#include <GenClass\fpml-com-5-4\CommodityPhysicalQuantity.hpp>
#include <GenClass\fpml-com-5-4\CommodityPhysicalQuantityBase.hpp>
#include <GenClass\fpml-com-5-4\CommodityPhysicalQuantitySchedule.hpp>
#include <GenClass\fpml-com-5-4\CommodityPipeline.hpp>
#include <GenClass\fpml-com-5-4\CommodityPipelineCycle.hpp>
#include <GenClass\fpml-com-5-4\CommodityPremium.hpp>
#include <GenClass\fpml-com-5-4\CommodityPricingDates.hpp>
#include <GenClass\fpml-com-5-4\CommodityProductGrade.hpp>
#include <GenClass\fpml-com-5-4\CommodityQuantityFrequency.hpp>
#include <GenClass\fpml-com-5-4\CommodityRelativeExpirationDates.hpp>
#include <GenClass\fpml-com-5-4\CommodityRelativePaymentDates.hpp>
#include <GenClass\fpml-com-5-4\CommoditySettlementPeriodsNotionalQuantity.hpp>
#include <GenClass\fpml-com-5-4\CommoditySettlementPeriodsNotionalQuantitySchedule.hpp>
#include <GenClass\fpml-com-5-4\CommoditySettlementPeriodsPriceSchedule.hpp>
#include <GenClass\fpml-com-5-4\CommoditySpread.hpp>
#include <GenClass\fpml-com-5-4\CommoditySpreadSchedule.hpp>
#include <GenClass\fpml-com-5-4\CommodityStrikeSchedule.hpp>
#include <GenClass\fpml-com-5-4\CommoditySwap.hpp>
#include <GenClass\fpml-com-5-4\CommoditySwapLeg.hpp>
#include <GenClass\fpml-com-5-4\CommoditySwaption.hpp>
#include <GenClass\fpml-com-5-4\CommoditySwaptionUnderlying.hpp>
#include <GenClass\fpml-com-5-4\DataProvider.hpp>
#include <GenClass\fpml-com-5-4\DisruptionFallback.hpp>
#include <GenClass\fpml-com-5-4\EEPParameters.hpp>
#include <GenClass\fpml-com-5-4\EEPRiskPeriod.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDelivery.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDeliveryFirm.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDeliveryPeriods.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDeliveryPoint.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDeliverySystemFirm.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDeliveryType.hpp>
#include <GenClass\fpml-com-5-4\ElectricityDeliveryUnitFirm.hpp>
#include <GenClass\fpml-com-5-4\ElectricityPhysicalDeliveryQuantity.hpp>
#include <GenClass\fpml-com-5-4\ElectricityPhysicalDeliveryQuantitySchedule.hpp>
#include <GenClass\fpml-com-5-4\ElectricityPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\ElectricityPhysicalQuantity.hpp>
#include <GenClass\fpml-com-5-4\ElectricityProduct.hpp>
#include <GenClass\fpml-com-5-4\ElectricityTransmissionContingency.hpp>
#include <GenClass\fpml-com-5-4\ElectricityTransmissionContingencyType.hpp>
#include <GenClass\fpml-com-5-4\EnvironmentalPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\EnvironmentalProduct.hpp>
#include <GenClass\fpml-com-5-4\EnvironmentalProductApplicableLaw.hpp>
#include <GenClass\fpml-com-5-4\EnvironmentalProductComplaincePeriod.hpp>
#include <GenClass\fpml-com-5-4\EnvironmentalTrackingSystem.hpp>
#include <GenClass\fpml-com-5-4\FinancialSwapLeg.hpp>
#include <GenClass\fpml-com-5-4\FixedPrice.hpp>
#include <GenClass\fpml-com-5-4\FixedPriceLeg.hpp>
#include <GenClass\fpml-com-5-4\FloatingLegCalculation.hpp>
#include <GenClass\fpml-com-5-4\FloatingPriceLeg.hpp>
#include <GenClass\fpml-com-5-4\FloatingStrikePrice.hpp>
#include <GenClass\fpml-com-5-4\GasDelivery.hpp>
#include <GenClass\fpml-com-5-4\GasDeliveryPeriods.hpp>
#include <GenClass\fpml-com-5-4\GasDeliveryPoint.hpp>
#include <GenClass\fpml-com-5-4\GasPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\GasPhysicalQuantity.hpp>
#include <GenClass\fpml-com-5-4\GasProduct.hpp>
#include <GenClass\fpml-com-5-4\GasQuality.hpp>
#include <GenClass\fpml-com-5-4\Lag.hpp>
#include <GenClass\fpml-com-5-4\LagReference.hpp>
#include <GenClass\fpml-com-5-4\MarketDisruptionEvent.hpp>
#include <GenClass\fpml-com-5-4\Material.hpp>
#include <GenClass\fpml-com-5-4\Metal.hpp>
#include <GenClass\fpml-com-5-4\MetalDelivery.hpp>
#include <GenClass\fpml-com-5-4\MetalPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\NonPeriodicFixedPriceLeg.hpp>
#include <GenClass\fpml-com-5-4\OilDelivery.hpp>
#include <GenClass\fpml-com-5-4\OilPhysicalLeg.hpp>
#include <GenClass\fpml-com-5-4\OilPipelineDelivery.hpp>
#include <GenClass\fpml-com-5-4\OilProduct.hpp>
#include <GenClass\fpml-com-5-4\OilProductType.hpp>
#include <GenClass\fpml-com-5-4\OilTransferDelivery.hpp>
#include <GenClass\fpml-com-5-4\PercentageTolerance.hpp>
#include <GenClass\fpml-com-5-4\PhysicalForwardLeg.hpp>
#include <GenClass\fpml-com-5-4\PhysicalSwapLeg.hpp>
#include <GenClass\fpml-com-5-4\QuantityReference.hpp>
#include <GenClass\fpml-com-5-4\ReferenceLevel.hpp>
#include <GenClass\fpml-com-5-4\ReferenceLevelUnit.hpp>
#include <GenClass\fpml-com-5-4\SequencedDisruptionFallback.hpp>
#include <GenClass\fpml-com-5-4\SettlementPeriods.hpp>
#include <GenClass\fpml-com-5-4\SettlementPeriodsFixedPrice.hpp>
#include <GenClass\fpml-com-5-4\SettlementPeriodsReference.hpp>
#include <GenClass\fpml-com-5-4\SettlementPeriodsSchedule.hpp>
#include <GenClass\fpml-com-5-4\SettlementPeriodsStep.hpp>
#include <GenClass\fpml-com-5-4\UnitQuantity.hpp>
#include <GenClass\fpml-com-5-4\WeatherCalculationPeriod.hpp>
#include <GenClass\fpml-com-5-4\WeatherCalculationPeriods.hpp>
#include <GenClass\fpml-com-5-4\WeatherIndex.hpp>
#include <GenClass\fpml-com-5-4\WeatherIndexData.hpp>
#include <GenClass\fpml-com-5-4\WeatherLeg.hpp>
#include <GenClass\fpml-com-5-4\WeatherLegCalculation.hpp>
#include <GenClass\fpml-com-5-4\WeatherStation.hpp>
#include <GenClass\fpml-com-5-4\WeatherStationAirport.hpp>
#include <GenClass\fpml-com-5-4\WeatherStationWBAN.hpp>
#include <GenClass\fpml-com-5-4\WeatherStationWMO.hpp>
