#include <GenClass\fpml-ird-5-4\BondReference.hpp>
#include <GenClass\fpml-ird-5-4\BulletPayment.hpp>
#include <GenClass\fpml-ird-5-4\Calculation.hpp>
#include <GenClass\fpml-ird-5-4\CalculationPeriod.hpp>
#include <GenClass\fpml-ird-5-4\CalculationPeriodAmount.hpp>
#include <GenClass\fpml-ird-5-4\CalculationPeriodDates.hpp>
#include <GenClass\fpml-ird-5-4\CalculationPeriodDatesReference.hpp>
#include <GenClass\fpml-ird-5-4\CancelableProvision.hpp>
#include <GenClass\fpml-ird-5-4\CancelableProvisionAdjustedDates.hpp>
#include <GenClass\fpml-ird-5-4\CancellationEvent.hpp>
#include <GenClass\fpml-ird-5-4\CapFloor.hpp>
#include <GenClass\fpml-ird-5-4\Cashflows.hpp>
#include <GenClass\fpml-ird-5-4\CashPriceMethod.hpp>
#include <GenClass\fpml-ird-5-4\CashSettlement.hpp>
#include <GenClass\fpml-ird-5-4\CashSettlementPaymentDate.hpp>
#include <GenClass\fpml-ird-5-4\CrossCurrencyMethod.hpp>
#include <GenClass\fpml-ird-5-4\DateRelativeToCalculationPeriodDates.hpp>
#include <GenClass\fpml-ird-5-4\DateRelativeToPaymentDates.hpp>
#include <GenClass\fpml-ird-5-4\Discounting.hpp>
#include <GenClass\fpml-ird-5-4\EarlyTerminationEvent.hpp>
#include <GenClass\fpml-ird-5-4\EarlyTerminationProvision.hpp>
#include <GenClass\fpml-ird-5-4\ExerciseEvent.hpp>
#include <GenClass\fpml-ird-5-4\ExercisePeriod.hpp>
#include <GenClass\fpml-ird-5-4\ExtendibleProvision.hpp>
#include <GenClass\fpml-ird-5-4\ExtendibleProvisionAdjustedDates.hpp>
#include <GenClass\fpml-ird-5-4\ExtensionEvent.hpp>
#include <GenClass\fpml-ird-5-4\FallbackReferencePrice.hpp>
#include <GenClass\fpml-ird-5-4\FinalCalculationPeriodDateAdjustment.hpp>
#include <GenClass\fpml-ird-5-4\FloatingRateDefinition.hpp>
#include <GenClass\fpml-ird-5-4\Fra.hpp>
#include <GenClass\fpml-ird-5-4\FxFixingDate.hpp>
#include <GenClass\fpml-ird-5-4\FxLinkedNotionalAmount.hpp>
#include <GenClass\fpml-ird-5-4\FxLinkedNotionalSchedule.hpp>
#include <GenClass\fpml-ird-5-4\InflationRateCalculation.hpp>
#include <GenClass\fpml-ird-5-4\InterestRateStream.hpp>
#include <GenClass\fpml-ird-5-4\InterestRateStreamReference.hpp>
#include <GenClass\fpml-ird-5-4\MandatoryEarlyTermination.hpp>
#include <GenClass\fpml-ird-5-4\MandatoryEarlyTerminationAdjustedDates.hpp>
#include <GenClass\fpml-ird-5-4\NonDeliverableSettlement.hpp>
#include <GenClass\fpml-ird-5-4\Notional.hpp>
#include <GenClass\fpml-ird-5-4\NotionalStepRule.hpp>
#include <GenClass\fpml-ird-5-4\OptionalEarlyTermination.hpp>
#include <GenClass\fpml-ird-5-4\OptionalEarlyTerminationAdjustedDates.hpp>
#include <GenClass\fpml-ird-5-4\PaymentCalculationPeriod.hpp>
#include <GenClass\fpml-ird-5-4\PaymentDates.hpp>
#include <GenClass\fpml-ird-5-4\PaymentDatesReference.hpp>
#include <GenClass\fpml-ird-5-4\PriceSourceDisruption.hpp>
#include <GenClass\fpml-ird-5-4\PrincipalExchange.hpp>
#include <GenClass\fpml-ird-5-4\RelevantUnderlyingDateReference.hpp>
#include <GenClass\fpml-ird-5-4\ResetDates.hpp>
#include <GenClass\fpml-ird-5-4\ResetDatesReference.hpp>
#include <GenClass\fpml-ird-5-4\SettlementProvision.hpp>
#include <GenClass\fpml-ird-5-4\SettlementRateOption.hpp>
#include <GenClass\fpml-ird-5-4\SinglePartyOption.hpp>
#include <GenClass\fpml-ird-5-4\StubCalculationPeriodAmount.hpp>
#include <GenClass\fpml-ird-5-4\Swap.hpp>
#include <GenClass\fpml-ird-5-4\SwapAdditionalTerms.hpp>
#include <GenClass\fpml-ird-5-4\Swaption.hpp>
#include <GenClass\fpml-ird-5-4\SwaptionAdjustedDates.hpp>
#include <GenClass\fpml-ird-5-4\SwaptionPhysicalSettlement.hpp>
#include <GenClass\fpml-ird-5-4\ValuationDatesReference.hpp>
#include <GenClass\fpml-ird-5-4\ValuationPostponement.hpp>
#include <GenClass\fpml-ird-5-4\YieldCurveMethod.hpp>
