#include <GenClass\fpml-eq-shared-5-4\AdditionalDisruptionEvents.hpp>
#include <GenClass\fpml-eq-shared-5-4\AdditionalPaymentAmount.hpp>
#include <GenClass\fpml-eq-shared-5-4\AdjustableDateOrRelativeDateSequence.hpp>
#include <GenClass\fpml-eq-shared-5-4\BoundedCorrelation.hpp>
#include <GenClass\fpml-eq-shared-5-4\BoundedVariance.hpp>
#include <GenClass\fpml-eq-shared-5-4\CalculatedAmount.hpp>
#include <GenClass\fpml-eq-shared-5-4\CalculationFromObservation.hpp>
#include <GenClass\fpml-eq-shared-5-4\Compounding.hpp>
#include <GenClass\fpml-eq-shared-5-4\CompoundingRate.hpp>
#include <GenClass\fpml-eq-shared-5-4\Correlation.hpp>
#include <GenClass\fpml-eq-shared-5-4\DirectionalLeg.hpp>
#include <GenClass\fpml-eq-shared-5-4\DirectionalLegUnderlyer.hpp>
#include <GenClass\fpml-eq-shared-5-4\DirectionalLegUnderlyerValuation.hpp>
#include <GenClass\fpml-eq-shared-5-4\DividendAdjustment.hpp>
#include <GenClass\fpml-eq-shared-5-4\DividendConditions.hpp>
#include <GenClass\fpml-eq-shared-5-4\DividendPaymentDate.hpp>
#include <GenClass\fpml-eq-shared-5-4\DividendPeriod.hpp>
#include <GenClass\fpml-eq-shared-5-4\DividendPeriodDividend.hpp>
#include <GenClass\fpml-eq-shared-5-4\EquityCorporateEvents.hpp>
#include <GenClass\fpml-eq-shared-5-4\EquityPremium.hpp>
#include <GenClass\fpml-eq-shared-5-4\EquityStrike.hpp>
#include <GenClass\fpml-eq-shared-5-4\EquityValuation.hpp>
#include <GenClass\fpml-eq-shared-5-4\ExtraordinaryEvents.hpp>
#include <GenClass\fpml-eq-shared-5-4\FloatingRateCalculationReference.hpp>
#include <GenClass\fpml-eq-shared-5-4\IndexAdjustmentEvents.hpp>
#include <GenClass\fpml-eq-shared-5-4\InterestCalculation.hpp>
#include <GenClass\fpml-eq-shared-5-4\InterestLeg.hpp>
#include <GenClass\fpml-eq-shared-5-4\InterestLegCalculationPeriodDates.hpp>
#include <GenClass\fpml-eq-shared-5-4\InterestLegCalculationPeriodDatesReference.hpp>
#include <GenClass\fpml-eq-shared-5-4\InterestLegResetDates.hpp>
#include <GenClass\fpml-eq-shared-5-4\LegAmount.hpp>
#include <GenClass\fpml-eq-shared-5-4\LegId.hpp>
#include <GenClass\fpml-eq-shared-5-4\LegIdentifier.hpp>
#include <GenClass\fpml-eq-shared-5-4\MakeWholeProvisions.hpp>
#include <GenClass\fpml-eq-shared-5-4\NettedSwapBase.hpp>
#include <GenClass\fpml-eq-shared-5-4\OptionFeatures.hpp>
#include <GenClass\fpml-eq-shared-5-4\PrincipalExchangeAmount.hpp>
#include <GenClass\fpml-eq-shared-5-4\PrincipalExchangeDescriptions.hpp>
#include <GenClass\fpml-eq-shared-5-4\PrincipalExchangeFeatures.hpp>
#include <GenClass\fpml-eq-shared-5-4\Representations.hpp>
#include <GenClass\fpml-eq-shared-5-4\Return.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnLeg.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnLegValuation.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnLegValuationPrice.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwap.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapAdditionalPayment.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapAmount.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapBase.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapEarlyTermination.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapLegUnderlyer.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapNotional.hpp>
#include <GenClass\fpml-eq-shared-5-4\ReturnSwapPaymentDates.hpp>
#include <GenClass\fpml-eq-shared-5-4\StartingDate.hpp>
#include <GenClass\fpml-eq-shared-5-4\StubCalculationPeriod.hpp>
#include <GenClass\fpml-eq-shared-5-4\Variance.hpp>
