#include <GenClass\fpml-msg-5-4\AdditionalData.hpp>
#include <GenClass\fpml-msg-5-4\Acknowledgement.hpp>
#include <GenClass\fpml-msg-5-4\BusinessProcess.hpp>
#include <GenClass\fpml-msg-5-4\CorrectableRequestMessage.hpp>
#include <GenClass\fpml-msg-5-4\CorrelationId.hpp>
#include <GenClass\fpml-msg-5-4\EventIdentifier.hpp>
#include <GenClass\fpml-msg-5-4\EventStatus.hpp>
#include <GenClass\fpml-msg-5-4\EventStatusItem.hpp>
#include <GenClass\fpml-msg-5-4\EventStatusResponse.hpp>
#include <GenClass\fpml-msg-5-4\Exception.hpp>
#include <GenClass\fpml-msg-5-4\ExceptionMessageHeader.hpp>
#include <GenClass\fpml-msg-5-4\Message.hpp>
#include <GenClass\fpml-msg-5-4\MessageAddress.hpp>
#include <GenClass\fpml-msg-5-4\MessageHeader.hpp>
#include <GenClass\fpml-msg-5-4\MessageId.hpp>
#include <GenClass\fpml-msg-5-4\NonCorrectableRequestMessage.hpp>
#include <GenClass\fpml-msg-5-4\NotificationMessage.hpp>
#include <GenClass\fpml-msg-5-4\NotificationMessageHeader.hpp>
#include <GenClass\fpml-msg-5-4\ImplementationSpecification.hpp>
#include <GenClass\fpml-msg-5-4\ImplementationSpecificationVersion.hpp>
#include <GenClass\fpml-msg-5-4\PartyMessageInformation.hpp>
#include <GenClass\fpml-msg-5-4\PortfolioReference.hpp>
#include <GenClass\fpml-msg-5-4\PortfolioConstituentReference.hpp>
#include <GenClass\fpml-msg-5-4\PortfolioReferenceBase.hpp>
#include <GenClass\fpml-msg-5-4\ProblemLocation.hpp>
#include <GenClass\fpml-msg-5-4\Reason.hpp>
#include <GenClass\fpml-msg-5-4\ReasonCode.hpp>
#include <GenClass\fpml-msg-5-4\RequestEventStatus.hpp>
#include <GenClass\fpml-msg-5-4\RequestMessage.hpp>
#include <GenClass\fpml-msg-5-4\RequestMessageHeader.hpp>
#include <GenClass\fpml-msg-5-4\RequestRetransmission.hpp>
#include <GenClass\fpml-msg-5-4\ReportId.hpp>
#include <GenClass\fpml-msg-5-4\ReportIdentification.hpp>
#include <GenClass\fpml-msg-5-4\ReportSectionIdentification.hpp>
#include <GenClass\fpml-msg-5-4\ResponseMessage.hpp>
#include <GenClass\fpml-msg-5-4\ResponseMessageHeader.hpp>
#include <GenClass\fpml-msg-5-4\ServiceAdvisory.hpp>
#include <GenClass\fpml-msg-5-4\ServiceAdvisoryCategory.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\ServiceNotification.hpp>
#include <GenClass\fpml-msg-5-4\ServiceProcessingCycle.hpp>
#include <GenClass\fpml-msg-5-4\ServiceProcessingEvent.hpp>
#include <GenClass\fpml-msg-5-4\ServiceProcessingStatus.hpp>
#include <GenClass\fpml-msg-5-4\ServiceProcessingStep.hpp>
#include <GenClass\fpml-msg-5-4\ServiceStatus.hpp>
#include <GenClass\fpml-msg-5-4\UnprocessedElementWrapper.hpp>
#include <GenClass\fpml-msg-5-4\VerificationStatus.hpp>
#include <GenClass\fpml-msg-5-4\VerificationStatusNotification.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
#include <GenClass\fpml-msg-5-4\.hpp>
