#include <GenClass\fpml-riskdef-5-4\AssetOrTermPointOrPricingStructureReference.hpp>
#include <GenClass\fpml-riskdef-5-4\BasicAssetValuation.hpp>
#include <GenClass\fpml-riskdef-5-4\DenominatorTerm.hpp>
#include <GenClass\fpml-riskdef-5-4\DerivativeCalculationMethod.hpp>
#include <GenClass\fpml-riskdef-5-4\DerivativeCalculationProcedure.hpp>
#include <GenClass\fpml-riskdef-5-4\DerivativeFormula.hpp>
#include <GenClass\fpml-riskdef-5-4\FormulaTerm.hpp>
#include <GenClass\fpml-riskdef-5-4\GenericDimension.hpp>
#include <GenClass\fpml-riskdef-5-4\InstrumentSet.hpp>
#include <GenClass\fpml-riskdef-5-4\Market.hpp>
#include <GenClass\fpml-riskdef-5-4\MarketReference.hpp>
#include <GenClass\fpml-riskdef-5-4\PerturbationType.hpp>
#include <GenClass\fpml-riskdef-5-4\PositionId.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingDataPointCoordinate.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingDataPointCoordinateReference.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingInputReplacement.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingInputType.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingMethod.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingParameterDerivative.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingParameterDerivativeReference.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingParameterShift.hpp>
#include <GenClass\fpml-riskdef-5-4\PricingStructureValuation.hpp>
#include <GenClass\fpml-riskdef-5-4\QuotedAssetSet.hpp>
#include <GenClass\fpml-riskdef-5-4\SensitivityDefinition.hpp>
#include <GenClass\fpml-riskdef-5-4\SensitivitySetDefinition.hpp>
#include <GenClass\fpml-riskdef-5-4\SensitivitySetDefinitionReference.hpp>
#include <GenClass\fpml-riskdef-5-4\TimeDimension.hpp>
#include <GenClass\fpml-riskdef-5-4\Valuation.hpp>
#include <GenClass\fpml-riskdef-5-4\ValuationReference.hpp>
#include <GenClass\fpml-riskdef-5-4\ValuationScenario.hpp>
#include <GenClass\fpml-riskdef-5-4\ValuationScenarioReference.hpp>
#include <GenClass\fpml-riskdef-5-4\WeightedPartialDerivative.hpp>
